## This is pyTorch tutorial from here:

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

last updated: 2023-08-21 by JT



In [1]:
import torch
import numpy as np

In [6]:
#Initializing tensors

# Directly from data:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(data)
print(x_data)

# From numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
